// ============================================================
// S SQUARE SALES DASHBOARD - DASHBOARD 1 + DASHBOARD 2
// Google Sheet -> GitHub Pages
// DATA column is used to identify TARGET / SALE / RETURN rows.
// ============================================================

const CSV_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQkx61LU5M5w6cafCI36sVjmFbBZ5lK2krxwI-uxLsblvc0RBX5YHk7C9iKFbQvYM9RAcFQwYcuIdkn/pub?gid=1181069336&single=true&output=csv";
let allData=[];let charts={};
const d1FilterDefs={typeFilter:["TYPE","TYPE"],agentFilter:["AGENT NAME","AGENT NAME"],brandFilter:["BRAND NAME","BRAND NAME"],dealerFilter:["DEALER NAME","DEALER NAME"],monthFilter:["MONTH","MONTH"],yearFilter:["YEAR","YEAR"],quarterFilter:["FY Quarter","FY QUARTER"],fyFilter:["F YEAR","F YEAR"],seasonFilter:["SEASON","SEASON"]};
const d1Selected={};Object.keys(d1FilterDefs).forEach(k=>d1Selected[k]=new Set());

function parseCSV(text){const rows=[];let row=[],value="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){value+='"';i++;}else if(c==='"'){q=!q;}else if(c===','&&!q){row.push(value.trim());value="";}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(value.trim());if(row.some(x=>x!==""))rows.push(row);row=[];value="";}else value+=c;}if(value!==""||row.length){row.push(value.trim());if(row.some(x=>x!==""))rows.push(row);}if(!rows.length)return[];const headers=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>{const o={};headers.forEach((h,i)=>o[h]=r[i]||"");return o;});}
function num(v){if(v==null)return 0;const n=parseFloat(String(v).replace(/₹/g,'').replace(/,/g,'').replace(/\s/g,''));return isNaN(n)?0:n;}
function money(v){v=Number(v)||0;if(v>=1e7)return '₹ '+(v/1e7).toFixed(2)+' Cr';if(v>=1e5)return '₹ '+(v/1e5).toFixed(2)+' L';return '₹ '+v.toLocaleString('en-IN',{maximumFractionDigits:0});}
function numberFmt(v){return Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0});}
function pct(v){return (Number(v)||0).toFixed(2)+'%';}
function norm(v){return String(v||'').trim().toUpperCase();}
function dataType(row){const s=norm(row['DATA']);if(s.includes('TARGET'))return 'TARGET';if(s.includes('RETURN'))return 'RETURN';if(s.includes('SALE'))return 'SALE';return 'SALE';}
function targetOf(row){return dataType(row)==='TARGET'?num(row['VALUE']):0;}
function saleOf(row){return dataType(row)==='SALE'?num(row['VALUE']):0;}
function returnOf(row){return dataType(row)==='RETURN'?Math.abs(num(row['VALUE'])):0;}
function qtySaleOf(row){return dataType(row)==='SALE'?num(row['QTY']):0;}
function qtyReturnOf(row){return dataType(row)==='RETURN'?Math.abs(num(row['QTY'])):0;}
function netOf(row){return saleOf(row)-returnOf(row);}

async function loadData(){try{const r=await fetch(CSV_URL+'&t='+Date.now());if(!r.ok)throw Error('Google Sheet load failed');allData=parseCSV(await r.text());setupD1Filters();updateDashboard1();}catch(e){console.error(e);alert('Google Sheet se data load nahi ho pa raha hai. Published CSV link check karein.');}}

function setupD1Filters(){Object.entries(d1FilterDefs).forEach(([id,[col,label]])=>{const old=document.getElementById(id);if(old)old.remove();const box=document.createElement('div');box.className='filter-box';box.id=id;box.innerHTML=`<button type="button" class="filter-button"><span>All ${label}</span><span>⌄</span></button><div class="filter-dropdown"></div>`;document.getElementById('d1Filters').appendChild(box);box.querySelector('.filter-button').onclick=e=>{e.stopPropagation();toggleD1Filter(id);};const menu=box.querySelector('.filter-dropdown');const search=document.createElement('input');search.className='filter-search';search.placeholder='🔍 Search...';menu.appendChild(search);const allLabel=document.createElement('label');allLabel.className='filter-option filter-all';allLabel.innerHTML='<input type="checkbox" checked> All';menu.appendChild(allLabel);const list=document.createElement('div');menu.appendChild(list);const vals=[...new Set(allData.map(r=>String(r[col]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));vals.forEach(v=>{const l=document.createElement('label');l.className='filter-option';l.innerHTML=`<input type="checkbox" value="${escapeHtml(v)}"> ${escapeHtml(v)}`;list.appendChild(l);});const allCb=allLabel.querySelector('input');allCb.onchange=()=>{if(allCb.checked){d1Selected[id].clear();list.querySelectorAll('input').forEach(x=>x.checked=false);updateD1Button(id,label);updateDashboard1();}};list.querySelectorAll('input').forEach(cb=>cb.onchange=()=>{if(cb.checked)d1Selected[id].add(cb.value);else d1Selected[id].delete(cb.value);allCb.checked=d1Selected[id].size===0;updateD1Button(id,label);updateDashboard1();});search.oninput=()=>{const s=search.value.toLowerCase();list.querySelectorAll('label').forEach(l=>l.style.display=l.textContent.toLowerCase().includes(s)?'flex':'none');};});}
function escapeHtml(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function toggleD1Filter(id){const target=document.getElementById(id);document.querySelectorAll('#d1Filters .filter-box').forEach(b=>{if(b!==target)b.classList.remove('open');});target.classList.toggle('open');}
document.addEventListener('click',e=>{if(!e.target.closest('.filter-box'))document.querySelectorAll('.filter-box').forEach(b=>b.classList.remove('open'));});
function updateD1Button(id,label){const b=document.querySelector('#'+id+' .filter-button span:first-child');const n=d1Selected[id].size;b.textContent=n?n+' Selected':'All '+label;}
function getD1Data(){return allData.filter(r=>Object.entries(d1FilterDefs).every(([id,[col]])=>!d1Selected[id].size||d1Selected[id].has(String(r[col]||'').trim())));}
function updateDashboard1(){const data=getD1Data();updateD1KPI(data);updateBrandChart(data);updateMonthChart(data);updateAgentChart(data);updateDealerChart(data);}
function updateD1KPI(data){let target=0,sale=0,ret=0;const dealers=new Set();data.forEach(r=>{target+=targetOf(r);sale+=saleOf(r);ret+=returnOf(r);if(r['DEALER NAME'])dealers.add(r['DEALER NAME']);});const net=sale-ret;document.getElementById('targetValue').textContent=money(target);document.getElementById('saleValue').textContent=money(sale);document.getElementById('returnValue').textContent=money(ret);document.getElementById('netSaleValue').textContent=money(net);document.getElementById('achievePercent').textContent=pct(target?net/target*100:0);document.getElementById('returnPercent').textContent=pct(sale?ret/sale*100:0);document.getElementById('dealerCount').textContent=numberFmt(dealers.size);}
function chartOptions(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'top'},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{y:{beginAtZero:true,ticks:{callback:v=>money(v)}}}};}
function makeChart(id,type,labels,datasets,opts={}){const c=document.getElementById(id);if(!c)return;if(charts[id])charts[id].destroy();charts[id]=new Chart(c,{type,data:{labels,datasets},options:{...chartOptions(),...opts}});}
function grouped(data,col){const m={};data.forEach(r=>{const k=r[col]||'Blank';if(!m[k])m[k]={target:0,net:0};m[k].target+=targetOf(r);m[k].net+=netOf(r);});return m;}
function updateBrandChart(data){const g=grouped(data,'BRAND NAME');const labels=Object.keys(g).sort((a,b)=>g[b].net-g[a].net);const inner=document.querySelector('.brand-chart-inner');inner.style.minWidth=Math.max(900,labels.length*90)+'px';makeChart('brandChart','bar',labels,[{label:'Target',data:labels.map(x=>g[x].target),borderWidth:1,borderRadius:4},{label:'Net Sale',data:labels.map(x=>g[x].net),borderWidth:1,borderRadius:4}],{scales:{y:{beginAtZero:true,ticks:{callback:v=>money(v)}}}});}
function monthOrder(){return ['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'];}
function updateMonthChart(data){const g={};data.forEach(r=>{const k=r['MONTH']||'Blank';if(!g[k])g[k]={target:0,net:0};g[k].target+=targetOf(r);g[k].net+=netOf(r);});const labels=[...monthOrder().filter(m=>g[m]),...Object.keys(g).filter(m=>!monthOrder().includes(m))];makeChart('monthChart','line',labels,[{label:'Net Sale',data:labels.map(x=>g[x].net),borderWidth:3,tension:.3,fill:false},{label:'Target',data:labels.map(x=>g[x].target),borderWidth:3,borderDash:[8,5],tension:.3,fill:false}],{scales:{y:{beginAtZero:true,ticks:{callback:v=>money(v)}}}});}
function updateAgentChart(data){const g=grouped(data,'AGENT NAME');const labels=Object.keys(g).sort((a,b)=>g[b].net-g[a].net);makeChart('agentChart','bar',labels,[{label:'Target',data:labels.map(x=>g[x].target),borderWidth:1,borderRadius:4},{label:'Net Sale',data:labels.map(x=>g[x].net),borderWidth:1,borderRadius:4}],{scales:{y:{beginAtZero:true,ticks:{callback:v=>money(v)}}}});}
function updateDealerChart(data){const g=grouped(data,'DEALER NAME');const labels=Object.keys(g).sort((a,b)=>g[b].net-g[a].net).slice(0,20);makeChart('dealerChart','bar',labels,[{label:'Net Sale',data:labels.map(x=>g[x].net),borderWidth:1,borderRadius:4}],{scales:{y:{beginAtZero:true,ticks:{callback:v=>money(v)}}}});}

// ================= DASHBOARD 2 =================
let d2Data=[],d2Headers=[];let d2Selected={fy:new Set(),type:new Set(),brand:new Set(),dealer:new Set()};
function showDashboard(n){document.getElementById('dashboard1').style.display=n===1?'block':'none';document.getElementById('dashboard2').style.display=n===2?'block':'none';document.querySelectorAll('.dash-tab').forEach((b,i)=>b.classList.toggle('active',i===n-1));if(n===2&&!d2Data.length)loadDashboard2();}
function toggleMulti(id){const b=document.getElementById(id);document.querySelectorAll('.multi-select').forEach(x=>{if(x!==b)x.classList.remove('open')});b.classList.toggle('open');}
document.addEventListener('click',e=>{if(!e.target.closest('.multi-select'))document.querySelectorAll('.multi-select').forEach(x=>x.classList.remove('open'));});
function d2FindColumn(names){const hs=d2Headers.map(h=>norm(h).replace(/[^A-Z0-9]/g,''));for(const n of names){const i=hs.indexOf(norm(n).replace(/[^A-Z0-9]/g,''));if(i>=0)return d2Headers[i];}return '';}
function d2Date(v){if(!v)return null;let s=String(v).trim(),m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);let d=m?new Date(+m[3],+m[2]-1,+m[1]):new Date(s);return isNaN(d)?null:d;}
function d2FY(r){const c=d2FindColumn(['F YEAR','FY','Financial Year']);if(c&&r[c])return String(r[c]).trim();const dc=d2FindColumn(['DATE','Invoice Date','Sales Date']);const d=d2Date(r[dc]);if(!d)return '';const y=d.getFullYear(),m=d.getMonth()+1;return m>=4?y+'-'+String(y+1).slice(-2):(y-1)+'-'+String(y).slice(-2);}
function d2Values(type){if(type==='fy')return [...new Set(d2Data.map(d2FY).filter(Boolean))].sort().reverse();const map={type:['TYPE'],brand:['BRAND NAME','BRAND'],dealer:['DEALER NAME','DEALER']};const c=d2FindColumn(map[type]);return c?[...new Set(d2Data.map(r=>String(r[c]||'').trim()).filter(Boolean))].sort():[];}
function d2SetupMulti(type,id){const root=document.getElementById(id),menu=root.querySelector('.multi-menu'),button=root.querySelector('button');menu.innerHTML='';const search=document.createElement('input');search.className='multi-search';search.placeholder='🔍 Search...';menu.appendChild(search);const all=document.createElement('label');all.className='multi-all';all.innerHTML='<input type="checkbox" checked> All';menu.appendChild(all);const list=document.createElement('div');menu.appendChild(list);d2Values(type).forEach(v=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" value="${escapeHtml(v)}"> ${escapeHtml(v)}`;list.appendChild(l);});const allCb=all.querySelector('input');allCb.onchange=()=>{if(allCb.checked){d2Selected[type].clear();list.querySelectorAll('input').forEach(x=>x.checked=false);button.textContent='All '+type.toUpperCase()+' ▾';d2Update();}};list.querySelectorAll('input').forEach(cb=>cb.onchange=()=>{if(cb.checked)d2Selected[type].add(cb.value);else d2Selected[type].delete(cb.value);allCb.checked=d2Selected[type].size===0;button.textContent=d2Selected[type].size?d2Selected[type].size+' Selected ▾':'All '+type.toUpperCase()+' ▾';d2Update();});search.oninput=()=>{const s=search.value.toLowerCase();list.querySelectorAll('label').forEach(l=>l.style.display=l.textContent.toLowerCase().includes(s)?'block':'none');};}
function d2FilteredRows(){const from=document.getElementById('d2-from').value?new Date(document.getElementById('d2-from').value):null;const to=document.getElementById('d2-to').value?new Date(document.getElementById('d2-to').value+'T23:59:59'):null;const tc=d2FindColumn(['TYPE']),bc=d2FindColumn(['BRAND NAME','BRAND']),dc=d2FindColumn(['DEALER NAME','DEALER']),datec=d2FindColumn(['DATE','Invoice Date','Sales Date']);return d2Data.filter(r=>(!d2Selected.fy.size||d2Selected.fy.has(d2FY(r)))&&(!d2Selected.type.size||d2Selected.type.has(String(r[tc]||'').trim()))&&(!d2Selected.brand.size||d2Selected.brand.has(String(r[bc]||'').trim()))&&(!d2Selected.dealer.size||d2Selected.dealer.has(String(r[dc]||'').trim()))&&(!from&&!to||(d2Date(r[datec])&&(!from||d2Date(r[datec])>=from)&&(!to||d2Date(r[datec])<=to))));}
function d2UpdateKPI(rows){let t=0,s=0,r=0;const ds=new Set();rows.forEach(x=>{t+=targetOf(x);s+=saleOf(x);r+=returnOf(x);if(x['DEALER NAME'])ds.add(x['DEALER NAME']);});const n=s-r;document.getElementById('d2-target').textContent=money(t);document.getElementById('d2-sales').textContent=money(s);document.getElementById('d2-return').textContent=money(r);document.getElementById('d2-net').textContent=money(n);document.getElementById('d2-achieve').textContent=pct(t?n/t*100:0);document.getElementById('d2-return-pct').textContent=pct(s?r/s*100:0);document.getElementById('d2-dealers').textContent=numberFmt(ds.size);}
function d2BuildTable(rows){const table=document.getElementById('dashboard2-table');const bc=d2FindColumn(['BRAND NAME','BRAND']);let years=[...new Set(rows.map(d2FY).filter(Boolean))].sort((a,b)=>String(b).localeCompare(String(a),undefined,{numeric:true})).slice(0,3);const groups={};rows.forEach(r=>{const brand=String(r[bc]||'').trim(),fy=d2FY(r);if(!brand||!fy)return;const k=brand+'|'+fy;if(!groups[k])groups[k]={target:0,qty:0,net:0};groups[k].target+=targetOf(r);groups[k].qty+=qtySaleOf(r)-qtyReturnOf(r);groups[k].net+=netOf(r);});const brands=[...new Set(rows.map(r=>String(r[bc]||'').trim()).filter(Boolean))].sort();let h='<thead><tr><th rowspan="2">BRAND NAME</th>';years.forEach(y=>h+=`<th colspan="4">${y}</th>`);h+='<th colspan="2">GROWTH %</th></tr><tr>';years.forEach(()=>h+='<th>TARGET</th><th>NET QTY</th><th>NET VALUE</th><th>ACHIEVE %</th>');h+='<th>CY vs PY</th><th>PY vs 2Y AGO</th></tr></thead><tbody>';brands.forEach(b=>{const vals=years.map(y=>groups[b+'|'+y]||{target:0,qty:0,net:0});h+=`<tr><td>${escapeHtml(b)}</td>`;vals.forEach(v=>h+=`<td>${money(v.target)}</td><td>${numberFmt(v.qty)}</td><td>${money(v.net)}</td><td>${pct(v.target?v.net/v.target*100:0)}</td>`);let g1=vals.length>1&&vals[1].net!==0?(vals[0].net-vals[1].net)/Math.abs(vals[1].net)*100:null,g2=vals.length>2&&vals[2].net!==0?(vals[1].net-vals[2].net)/Math.abs(vals[2].net)*100:null;h+=`<td class="${g1==null?'':g1>=0?'growth-positive':'growth-negative'}">${g1==null?'—':pct(g1)+(g1>=0?' ↑':' ↓')}</td><td class="${g2==null?'':g2>=0?'growth-positive':'growth-negative'}">${g2==null?'—':pct(g2)+(g2>=0?' ↑':' ↓')}</td></tr>`;});table.innerHTML=h+'</tbody>';}
function d2Update(){const rows=d2FilteredRows();d2UpdateKPI(rows);d2BuildTable(rows);}
async function loadDashboard2(){try{const r=await fetch(CSV_URL+'&t='+Date.now());if(!r.ok)throw Error('load failed');const parsed=parseCSV(await r.text());d2Headers=Object.keys(parsed[0]||{});d2Data=parsed;d2SetupMulti('fy','d2-fy');d2SetupMulti('type','d2-type');d2SetupMulti('brand','d2-brand');d2SetupMulti('dealer','d2-dealer');document.getElementById('d2-from').onchange=d2Update;document.getElementById('d2-to').onchange=d2Update;d2Update();}catch(e){console.error(e);alert('Dashboard 2 ka Google Sheet data load nahi hua.');}}
function resetDashboard2(){d2Selected={fy:new Set(),type:new Set(),brand:new Set(),dealer:new Set()};document.querySelectorAll('#dashboard2 .multi-menu input[type=checkbox]').forEach(x=>x.checked=false);document.querySelectorAll('#dashboard2 .multi-select button').forEach((b,i)=>b.textContent=['All FY ▾','All TYPE ▾','All BRAND ▾','All DEALER ▾'][i]);document.getElementById('d2-from').value='';document.getElementById('d2-to').value='';d2Update();}

loadData();
